### ISSUE TITLE
Verificar Banco de Dados

### ISSUE THREAD

**Issue by rkdsa** [IF977/EncostAki#2]
1. Ler documentação do site de dados abertos (http://dados.recife.pe.gov.br/)
2. Estudar sobre os dados e como verificar o banco 
3. Tratamento de dados
4. Conectar API do BD no app

**Comment by eacj** [comment]
A api do banco de dados não será mais conectada como planejado, encontramos outro meio de fazer isso portanto, na iteração 2 criaremos outra issue sobre como será feito a conexão com o banco de dados. Isso foi decidido agora na iteração 2. Estou me referindo a atividade 4 dessa issue.
