### ISSUE TITLE
Feedback Cadastrar histórias no gitHub IT2

### ISSUE THREAD

**Issue by lsca** [IF977/EncostAki#24]
Eai galera, tudo certinho??

Uso de lable : OK
Milestones : OK
1 Issue por participante : OK
Descrição da issue : -0,2.

**Com relação a descrição das issues, descrevam todas as issues que forem cadastradas, algumas vocês descreveram, outras não**

Qualquer duvida só falar aqui. Caso concordem, só fechar a issue.

**Comment by pvls** [comment]
Certo, foi porque a gente ainda tava se adaptando a como usar as issues, valeu velho :)

**Comment by pvls** [comment]
Então no caso, a gente também pode fechar as issues da iteração 1?

**Comment by lsca** [comment]
Pode 👍
