### ISSUE TITLE
Deploy no heroku

### ISSUE THREAD

**Issue by pvls** [IF977/EncostAki#28]
Obs: Estamos com problemas relacionados a isso, a princípio acreditávamos que era o devise, mas não, era outra coisa, e estamos trabalhando pra tentar deixar tudo 100%.

**Comment by vinicius3w** [comment]
chegaram a tentar resolver isso na monitoria?



--
*Vinicius Cardoso Garcia*
[www: viniciusgarcia.me]-[arxiv: http://arxiv.org/a/garcia_v_1]-[twitter:
@vinicius3w <http://www.twitter.com/vinicius3w>]


*Wyrd biõ fui arccd.*

2017-11-03 12:23 GMT-03:00 Pedro Vinicius <notifications@github.com>:

**Comment by pvls** [comment]
Sim, foi lá que apareceram mais problemas ainda kkk.

**Comment by vinicius3w** [comment]
kkkk



--
*Vinicius Cardoso Garcia*
[www: viniciusgarcia.me]-[arxiv: http://arxiv.org/a/garcia_v_1]-[twitter:
@vinicius3w <http://www.twitter.com/vinicius3w>]


*Wyrd biõ fui arccd.*

**Comment by pvls** [comment]
Att: Encotramos o problema, finalmente, era no uso do helper de imagens que estava com a sintaxe incorreta, depois de dias achando que era outra coisa e.e.

**Comment by pvls** [comment]
Ps: eram parênteses e.e.

**Comment by vinicius3w** [comment]
hahahaha... massa..
ninugém bateu meu record de 16 horas por causa de uma digitação errada...

era algo como: ao invés de "method_missing", escrevi "method_misisng"




--
*Vinicius Cardoso Garcia*
[www: viniciusgarcia.me]-[arxiv: http://arxiv.org/a/garcia_v_1]-[twitter:
@vinicius3w <http://www.twitter.com/vinicius3w>]


*Wyrd biõ fui arccd.*

**Comment by eacj** [comment]
KKKKKKKKKKKKKKKKKKKKKKKKKKK

**Comment by pvls** [comment]
KKKKKKKKKKKKKKKKKKKKKKK
