### ISSUE TITLE
Criar scaffold de users e migrar para o banco

### ISSUE THREAD

**Issue by pvls** [IF977/EncostAki#7]
1. Criação de scaffold de usuários
2. Migrar para o banco de dados

**Comment by eacj** [comment]
Obs: Fizemos isso na iteração 1, porém agora usamos outro método, no caso, essa issue realmente foi concluída porém foi substituída. Estamos usando Devise agora. o Scaffold de Users ainda existe pra meios de verificação do monitor. Não está mais sendo utilizado no projeto para a iteração 2.
